### ISSUE TITLE
Suricata template creation doesn't create temp config properly

### ISSUE THREAD

**Issue by LouAlbano** [EmergingThreats/IDSDeathBlossom#20]
Suricata template generation doesn't append the proper Yaml for custom rulesets.

Steps to recreate:

:/opt/IDSDeathBlossom$ python /opt/IDSDeathBlossom/IDSDeathBlossom.py -c /opt/IDSDeathBlossom/config/config.yaml -R run -t "suricata-2.0.6-test-test" --pcappath="/tmp/test.pcap" --globallogdir=/tmp/log/ --glogoverride --reporton=ids --use-custom-rules  --target-opts="all:customrules=/tmp/20160824.070816.1149512942.rules" 

2016-08-25 12:14:54,993 - WARNING - cmd_wrapper - /opt/IDSDeathBlossom/IDSDeathBlossom.py +106 - there was an error executing ulimit -c unlimited; /opt/suricata206/bin/suricata -c /tmp/kIYPa3 -l /tmp/log/ -r /tmp/test.pcap -v --runmode=single --set "stream.checksum-validation=no"

25/8/2016 -- 12:14:54 - <Error> - [ERRCODE: SC_ERR_CONF_YAML_ERROR(240)] - Failed to parse configuration file at line 439: did not find expected key

Generated config /tmp/kIYPa3 doesn't include "rule-files:"

$ tail -n 5 /tmp/kIYPa3
napatech:
    hba: -1
    use-all-streams: yes
    streams: [1, 2, 3]
- /tmp/20160824.070816.1149512942.rules

Adding "rule-files:" to /opt/suricata206/etc/suricata206.template works.  I am thinking having the code append the  "rule-files:" key before "  - /tmp/20160824.070816.1149512942.rules" will be the best bet for a fix.

**Comment by travisbgreen** [comment]
fix in https://github.com/EmergingThreats/IDSDeathBlossom/pull/21

**Comment by travisbgreen** [comment]
fixed, maintainer pls close
