### ISSUE TITLE
Snort config template uses incorrect path

### ISSUE THREAD

**Issue by LouAlbano** [EmergingThreats/IDSDeathBlossom#25]
/opt/snort2990/etc$ grep '/opt/' snort2990.template 
preprocessor http_inspect: global iis_unicode_map /opt/snort2983/etc/unicode.map 1252 compress_depth 65535 decompress_depth 65535
dynamicpreprocessor directory /opt/snort2983/lib/snort_dynamicpreprocessor/
dynamicengine /opt/snort2983/lib/snort_dynamicengine/libsf_engine.so
include /opt/snort2983/etc/classification.config
include /opt/snort2983/etc/reference.config

**Comment by travisbgreen** [comment]
created pull request https://github.com/EmergingThreats/IDSDeathBlossom/pull/26 with fixes
